stages:
  - setup
  - lint
  - test
  - build

setup:
  tags: ["mac-ventura-preview"]
  stage: setup
  script:
    - echo "setupp"

lint:
  tags: ["mac-ventura-preview"]
  stage: lint
  script:
    - echo "coucou"
    - ls -la
    - uname -a
    - python3 --version
    - go version
    - env
    - ls $GOPATH/src/github.com

