stages:
  - setup
  - lint
  - test
  - build

setup:
  tags: ["mac-ventura-preview"]
  stage: setup
  script:
    - echo "setupp"
    - ./macos_builder_setup.sh

lint:
  tags: ["mac-ventura-preview"]
  stage: lint
  script:
    # Check https://github.com/DataDog/datadog-agent-macos-build/blob/master/scripts/builder_setup.sh for differences
    # The runners deps are installed here: https://github.com/DataDog/ci-platform-machine-images/blob/bad51a01794d30db8dc18ad6e9dd7bd6462bab9b/packer/macos/preview/ventura/build.pkr.hcl
    - |
      echo "PKG_CONFIG_VERSION $(pkg-config --version)
      RUBY_VERSION $(ruby --version)
      BUNDLER_VERSION $(bundler --version)
      PYTHON_VERSION $(python3 --version)
      RUST_VERSION $(rustc --version)
      RUSTUP_VERSION $(rustup dump-testament)
      CMAKE_VERSION $(cmake --version)"



