---
variables:
  DATADOG_AGENT_BUILDIMAGES_SUFFIX: ""
  DATADOG_AGENT_BUILDIMAGES: v31988376-bfbb3afb

default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - unknown_failure
      - api_failure
      - scheduler_failure
      - stale_schedule
      - data_integrity_failure

stages:
  - generation
  - trigger

generate_pipeline:
  stage: generation
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64$DATADOG_AGENT_BUILDIMAGES_SUFFIX:$DATADOG_AGENT_BUILDIMAGES
  tags: ["arch:amd64"]
  script:
    - inv gitlab.generate-pipeline --output-file generated.yml
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - generated.yml

trigger_pipeline:
  stage: trigger
  trigger:
    include:
      - artifact: generated.yml
        job: generate_pipeline
    strategy: depend