name: Sls Test Perf

on:
  pull_request:
    branches:
        - main
  push:
    branches:
        - dylan/sls-perf-test

jobs:
  performance-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - node-version: 18.12
            aws-runtime-name: "nodejs18.x"
    steps:
      - name: Checkout dd-trace-js
        uses: actions/checkout@v4
        with:
            repository: DataDog/dd-trace-js
            path: dd-trace-js
      - name: Checkout datadog-lambda-js
        uses: actions/checkout@v4
        with:
          repository: DataDog/datadog-lambda-js
          path: datadog-lambda-js
      - name: Install node-gyp
        run: |
          yarn global add node-gyp
      - name: Update package.json to the current ref
        run: |
          cd datadog-lambda-js
          yarn add --dev https://github.com/DataDog/dd-trace-js
      - name: Build the layer
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          cd datadog-lambda-js
          ./scripts/build_layers.sh
      - name: Performance tests
        uses: DylanLovesCoffee/dylan-sls-perf-test@dyl/test
        with:
          runtime_id: '${{ matrix.aws-runtime-name }}'
          layer_path: 'datadog-lambda-js/.layers/datadog_lambda_node${{ matrix.node-version }}.zip'
          layer_name: 'performance-tester-nodejs-${{ matrix.node-version }}'
          role: arn:aws:iam::425362996713:role/serverless-integration-test-lambda-role
        #   pr_number: ${{ github.event.pull_request.number }}
          pr_number: dylan-test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: sa-east-1
        #   DD_API_KEY: empty
          DD_API_KEY_SECRET_ARN: arn:aws:secretsmanager:sa-east-1:425362996713:secret:dylansecret-I2cXev
